## Reading a CSV file using Pandas

Pandas is typically used for working in tabular data (simliar to the data stored in a spreadsheet). Pandas provides helper functions to read data from various file formates like CSV, Excel spreadsheets, HTML tables, JSON, SQL and more. Let's download a file `italy-covid-daywise.txt` which contains daywise Covid-19 data for Italy in the following format:

```
date,new_cases,new_deaths,new_tests
2020-04-21,2256.0,454.0,28095.0
2020-04-22,2729.0,534.0,44248.0
2020-04-23,3370.0,437.0,37083.0
2020-04-24,2646.0,464.0,95273.0
2020-04-25,3021.0,420.0,38676.0
2020-04-26,2357.0,415.0,24113.0
2020-04-27,2324.0,260.0,26678.0
2020-04-28,1739.0,333.0,37554.0
...
```

This format of storing data is known as *comma separated values* or CSV. 

> **CSVs**: A comma-separated values (CSV) file is a delimited text file that uses a comma to separate values. Each line of the file is a data record. Each record consists of one or more fields, separated by commas. A CSV file typically stores tabular data (numbers and text) in plain text, in which case each line will have the same number of fields. (Wikipedia)


We'll download this file using the `urlretrieve` function from the `urllib.request` module.

from urllib.request import urlretrieve

urlretrieve('https://hub.jovian.ml/wp-content/uploads/2020/09/italy-covid-daywise.csv', 
            'italy-covid-daywise.csv')

To read the file, we can use the `read_csv` method from Pandas. Let's being by importing the Pandas library. It is typically imported with the alias `pd`.

In [1]:
import pandas as pd

In [2]:
covid_df = pd.read_csv("italy-covid-daywise.csv")

In [3]:
type(covid_df)

pandas.DataFrame

In [4]:
covid_df.dtypes

date              str
new_cases       int64
new_deaths      int64
new_tests     float64
dtype: object

In [5]:
covid_df

           date  new_cases  new_deaths  new_tests
0    31-12-2019          0           0        NaN
1    01-01-2020          0           0        NaN
2    02-01-2020          0           0        NaN
3    03-01-2020          0           0        NaN
4    04-01-2020          0           0        NaN
..          ...        ...         ...        ...
243  30-08-2020       1444           1    53541.0
244  31-08-2020       1365           4    42583.0
245  01-09-2020        996           6    54395.0
246  02-09-2020        975           8        NaN
247  03-09-2020       1326           6        NaN

[248 rows x 4 columns]

We can view some basic information about the data frame using the `.info` method.

In [6]:
covid_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        248 non-null    str
 1   new_cases   248 non-null    int64
 2   new_deaths  248 non-null    int64
 3   new_tests   135 non-null    float64
dtypes: float64(1), int64(2), str(1)
memory usage: 7.9 KB

In [7]:
covid_df.describe()

         new_cases  new_deaths     new_tests
count   248.000000  248.000000    135.000000
mean   1094.818548  143.133065  31699.674074
std    1554.508002  227.105538  11622.209757
min    -148.000000  -31.000000   7841.000000
25%     123.000000    3.000000  25259.000000
50%     342.000000   17.000000  29545.000000
75%    1371.750000  175.250000  37711.000000
max    6557.000000  971.000000  95273.000000

The `columns` property contains the list of columns within the data frame.

In [9]:
covid_df.columns

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='str')

You can also retrieve the number of rows and columns in the data frame using the `.shape` method

In [11]:
covid_df.shape

(248, 4)

Here's a summary of the functions & methods we've looked at so far:

* `pd.read_csv` - Read data from a CSV file into a Pandas `DataFrame` object
* `.info()` - View basic infomation about rows, columns & data types
* `.describe()` - View statistical information about numeric columns
* `.columns` - Get the list of column names
* `.shape` - Get the number of rows & columns as a tuple

## Retrieving data from a data frame

The first thing you might want to do is to retrieve data from this data frame e.g. the counts of a specific day or the 
list of values in a specific column. To do this, it might help to understand the internal representation of data in a data frame. Conceptually, you can think of a dataframe as a dictionary of lists: the keys are column names, and the values are lists/arrays containing data for the respective columns.

In [12]:
# Pandas format is simliar to this
covid_data_dict = {
    'date':       ['2020-08-30', '2020-08-31', '2020-09-01', '2020-09-02', '2020-09-03'],
    'new_cases':  [1444, 1365, 996, 975, 1326],
    'new_deaths': [1, 4, 6, 8, 6],
    'new_tests': [53541, 42583, 54395, None, None]
}

Representing data in the above format has a few benefits:

* All values in a column typically have the same type of value, so it's more efficient to store them in a single array.
* Retrieving the values for a particular row simply requires extracting the elements at a given index from each of the column arrays.
* The representation is more compact (column names are recorded only once) compared to other formats where you might use a dictionary for each row of data (example shown below).

In [13]:
# Pandas format is not similar to this
covid_data_list = [
    {'date': '2020-08-30', 'new_cases': 1444, 'new_deaths': 1, 'new_tests': 53541},
    {'date': '2020-08-31', 'new_cases': 1365, 'new_deaths': 4, 'new_tests': 42583},
    {'date': '2020-09-01', 'new_cases': 996, 'new_deaths': 6, 'new_tests': 54395},
    {'date': '2020-09-02', 'new_cases': 975, 'new_deaths': 8 },
    {'date': '2020-09-03', 'new_cases': 1326, 'new_deaths': 6},
]

With the dictionary of lists analogy in mind, we can now guess how we might be able to retrieve data from a data frame. for example, we can get a list of values from a specific column using the `[]` indexing notation.

In [15]:
covid_df['new_cases']

0         0
1         0
2         0
3         0
4         0
       ...
243    1444
244    1365
245     996
246     975
247    1326
Name: new_cases, Length: 248, dtype: int64

In [14]:
covid_data_dict['new_cases']

[1444, 1365, 996, 975, 1326]

In [17]:
covid_data_list['new_cases']

TypeError: list indices must be integers or slices, not str

In [18]:
type(covid_df['new_cases'])

pandas.Series

In [19]:
type(covid_data_dict['new_cases'])

list

Just like arrays, you can retrieve a specific value with a series using the indexing notation `[]`.

In [ ]:
covid_df['new_cases'][]